---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.8.5

platforms:
  - name: ubuntu-16.04
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.20"}]
  - name: ubuntu-18.04
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.20"}]

suites:
  - name: source
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "source"
  - name: package
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "package"
