---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  channel: stable
  product_name: chef
  product_version: 14.11.21
  deprecations_as_errors: false

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: source
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "source"
  - name: package
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "package"
